local base = {}

local util = require("neodark.util")

function base.setup(palette)
  local base_ = {
    Normal = { fg = palette.fg, bg = palette.bg },
    Comment = { fg = palette.grey, bg = palette.none, style = 'italic' },
    Constant = { fg = palette.yellow, bg = palette.none },
    String = { fg = palette.green, bg = palette.none },
    Character = { fg = palette.green, bg = palette.none },
    Number = { fg = palette.orange, bg = palette.none },
    Boolean = { fg = palette.blue, bg = palette.none },
    Float = { fg = palette.yellow, bg = palette.none },
    Identifier = { fg = palette.blue, bg = palette.none },
    Function = { fg = palette.yellow, bg = palette.none },
    Statement = { fg = palette.purple, bg = palette.none },
    Conditional = { fg = palette.yellow_2, bg = palette.none },
    Repeat = { fg = palette.purple, bg = palette.none },
    Label = { fg = palette.blue, bg = palette.none },
    Operator = { fg = palette.purple, bg = palette.none },
    Keyword = { fg = palette.purple, bg = palette.none },
    Exception = { fg = palette.purple, bg = palette.none },
    Preproc = { fg = palette.yellow, bg = palette.none },
    Include = { fg = palette.purple, bg = palette.none },
    Define = { fg = palette.purple, bg = palette.none },
    Title = { fg = palette.cyan, bg = palette.none },
    Macro = { fg = palette.purple, bg = palette.none },
    PreCondit = { fg = palette.blue, bg = palette.none },
    Type = { fg = palette.blue, bg = palette.none },
    StorageClass = { fg = palette.blue, bg = palette.none },
    Structure = { fg = palette.yellow, bg = palette.none },
    Typedef = { fg = palette.yellow, bg = palette.none },
    Special = { fg = palette.blue, bg = palette.none },
    SpecialComment = { fg = palette.grey, bg = palette.none, style = 'italic' },
    Error = { fg = palette.red, bg = palette.none },
    Todo = { fg = palette.purple, bg = palette.none },
    Underlined = { fg = palette.cyan, bg = palette.none },
    Cursor = { fg = palette.none, bg = palette.none, style = "reverse" },
    vCursor = { styel = "reverse" },
    iCursor = { styel = "reverse" },
    ColorColumn = { fg = palette.none, bg = palette.grey_4 },
    Conceal = { fg = palette.bufline_nord_blue, bg = palette.none },
    CursorColumn = { fg = palette.none, bg = palette.bg1 },
    CursorLine = { fg = palette.none, bg = palette.bg4 },
    CursorLineNr = { fg = palette.none, bg = palette.bg },
    Debug = { fg = palette.yellow },
    debugBreakpoint = { fg = palette.bg, bg = palette.red },
    debugPC = { fg = palette.bg0, bg = palette.green },
    Directory = { fg = palette.blue, bg = palette.none },
    DiffAdd = { fg = palette.grey_3, bg = palette.diff_add },
    DiffChange = { fg = palette.yellow, bg = palette.diff_change },
    DiffDelete = { fg = palette.grey_3, bg = palette.diff_delete },
    DiffText = { fg = palette.grey_3, bg = palette.diff_text },
    ErrorMsg = { fg = palette.red, bg = palette.none, style = "bold" },
    WarningMsg = { fg = palette.yellow, bg = palette.none },
    MoreMsg = {fg = palette.yellow },
    VertSplit = { fg = palette.bg4, bg = palette.none },
    Folded = { fg = palette.grey, bg = palette.none },
    FoldColumn = { fg = palette.none, bg = palette.none },
    Search = { fg = palette.bg, bg = palette.blue },
    IncSearch = { fg = palette.bg, bg = palette.orange },
    CurSearch = { fg = palette.bg, bg = palette.orange },
    LineNr = { fg = palette.grey_1, bg = palette.none },
    NonText = { fg = palette.grey, bg = palette.none },
    Pmenu = { fg = palette.fg, bg = palette.bg1 },
    PmenuSel = { fg = palette.none, bg = palette.bg3 },
    PmenuSbar = { fg = palette.none, bg = palette.bg1 },
    PmenuThumb = { fg = palette.none, bg = palette.grey },
    Question = { fg = palette.yellow, bg = palette.none },
    QuickFixLine = { fg = palette.grey_3, bg = palette.orange },
    SignColumn = { fg = palette.bg, bg = palette.bg },
    SpecialKey = { fg = palette.grey, bg = palette.none },
    SpellBad = { fg = palette.red, bg = palette.none },
    SpellCap = { fg = palette.orange, bg = palette.none },
    SpellLocal = { fg = palette.blue, bg = palette.none },
    SpellRare = { fg = palette.purple, bg = palette.none },
    Substitute = { fg = palette.bg, bg = palette.green },
    TabLine = { fg = palette.fg, bg = palette.bg1 },
    TabLineSel = { fg = palette.fg, bg = palette.bg, style = "bold" },
    TabLineFill = { fg = palette.grey, bg = palette.bg1 },
    Terminal = { fg = palette.fg, bg = palette.bg },
    ToolbarBurron = { fg = palette.bg, bg = palette.bg_blue },
    Visual = { fg = palette.none, bg = palette.bg3 },
    Whitespace = { fg = palette.grey },
    VisualNOS = { fg = palette.none, bg = palette.bg2, style = "underline" },
    WildMenu = { fg = palette.bg, bg = palette.blue },
    EndOfBuffer = { fg = palette.bg, bg = palette.none },
    -- FloatBorder = { fg = palette.blue, bg = palette.bg },
    -- NormalFloat = { fg = palette.fg, bg = palette.bg },
    FloatBorder = { fg = palette.bg_d, bg = palette.bg_d },
    NormalFloat = { fg = palette.fg, bg = palette.bg_d },
    MatchParen = { fg = palette.none, bg = palette.grey },
  }

  return base_
end

return base
