local treesitter = {}

function treesitter.setup(palette)
  local treesitter_ = {
    ["@error"] = { fg = palette.red },
    ["@punctuation.delimiter"] = { fg = palette.blue },
    ["@punctuation.bracket"] = { fg = palette.cyan },
    ["@punctuation.special"] = { fg = palette.blue },
    ["@constant"] = { fg = palette.yellow },
    ["@constant.builtin"] = { fg = palette.orange },
    ["@constant.macro"] = { fg = palette.red },
    ["@string.regex"] = { fg = palette.green },
    ["@string"] = { fg = palette.green },
    ["@string.escape"] = { fg = palette.red },
    ["@character"] = { fg = palette.green },
    ["@number"] = { fg = palette.orange },
    ["@boolean"] = { fg = palette.orange },
    ["@float"] = { fg = palette.green },
    ["@annotation"] = { fg = palette.yellow },
    ["@attribute"] = { fg = palette.red },
    ["@namespace"] = { fg = palette.purple },
    ["@function"] = { fg = palette.blue },
    ["@function.builtin"] = { fg = palette.blue },
    ["@function.macro"] = { fg = palette.yellow },
    ["@parameter"] = { fg = palette.orange },
    ["@parameter.reference"] = { fg = palette.cyan },
    ["@method"] = { fg = palette.blue },
    ["@field"] = { fg = palette.cyan },
    ["@property"] = { fg = palette.blue },
    ["@constructor"] = { fg = palette.yellow },
    ["@conditional"] = { fg = palette.purple },
    ["@repeat"] = { fg = palette.purple },
    ["@label"] = { fg = palette.blue },
    ["@keyword"] = { fg = palette.purple },
    ["@keyword.function"] = { fg = palette.purple },
    ["@keyword.operator"] = { fg = palette.purple },
    ["@operator"] = { fg = palette.cyan },
    ["@exception"] = { fg = palette.purple },
    ["@type"] = { fg = palette.blue },
    ["@type.builtin"] = { fg = palette.blue },
    ["@structure"] = { fg = palette.purple },
    ["@include"] = { fg = palette.purple },
    ["@variable"] = { fg = palette.fg },
    ["@variable.builtin"] = { fg = palette.red },
    ["@text"] = { fg = palette.fg },
    ["@text.strong"] = { fg = palette.fg },
    ["@text.emphasis"] = { fg = palette.fg },
    ["@text.underline"] = { fg = palette.fg },
    ["@text.title"] = { fg = palette.cyan },
    ["@text.literal"] = { fg = palette.blue },
    ["@text.uri"] = { fg = palette.cyan },
    ["@tag"] = { fg = palette.purple },
    ["@tag.delimiter"] = { fg = palette.blue },
    ["@tag.attribute"] = { fg = palette.blue },

    rainbowcol1 = { fg = 'Gold' },
    rainbowcol2 = { fg = 'Orchid' },
    rainbowcol3 = { fg = 'LightSkyBlue' },
    rainbowcol4 = { fg = 'Gold' },
    rainbowcol5 = { fg = 'Orchid' },
    rainbowcol6 = { fg = 'LightSkyBlue' },
    rainbowcol7 = { fg = 'Orchid' },

    markdownTSLiteral = { fg = palette.blue },
    markdown_inlineTSLiteral = { fg = palette.blue }
  }

  return treesitter_
end

return treesitter
